# Generated by scripts/generate.py. Do not edit by hand.
"""One typed function per contract/manifest.json entry, grouped by
call shape: request-reply returns the response directly,
server-stream/duplex return an iterator of response chunks.

Each function only builds the wire payload and validates the reply —
it takes a `Transport` to actually speak the wire protocol, which this
package does not implement (see qvac._transport.Transport).
"""

from __future__ import annotations

from typing import Iterable, Iterator

from .._transport import Transport
from . import (
    BciTranscribeRequest,
    BciTranscribeResponse,
    BciTranscribeStreamRequest,
    BciTranscribeStreamResponse,
    CancelRequest,
    CancelResponse,
    ClassifyRequest,
    ClassifyResponse,
    CompletionStreamRequest,
    CompletionStreamResponse,
    DeleteCacheRequest,
    DeleteCacheResponse,
    DiffusionStreamRequest,
    DiffusionStreamResponse,
    DownloadAssetRequest,
    DownloadAssetResponse,
    EmbedRequest,
    EmbedResponse,
    FinetuneProgressResponse,
    FinetuneRequest,
    FinetuneResponse,
    GetLoadedModelInfoRequest,
    GetLoadedModelInfoResponse,
    GetModelInfoRequest,
    GetModelInfoResponse,
    HeartbeatRequest,
    HeartbeatResponse,
    LoadModelRequest,
    LoadModelResponse,
    LoggingStreamRequest,
    LoggingStreamResponse,
    ModelProgressResponse,
    ModelRegistryGetModelRequest,
    ModelRegistryGetModelResponse,
    ModelRegistryListRequest,
    ModelRegistryListResponse,
    ModelRegistrySearchRequest,
    ModelRegistrySearchResponse,
    OcrStreamRequest,
    OcrStreamResponse,
    PluginInvokeRequest,
    PluginInvokeResponse,
    PluginInvokeStreamRequest,
    PluginInvokeStreamResponse,
    ProvideRequest,
    ProvideResponse,
    RagProgressResponse,
    RagRequest,
    RagResponse,
    ResumeRequest,
    ResumeResponse,
    StateRequest,
    StateResponse,
    StopProvideRequest,
    StopProvideResponse,
    SuspendRequest,
    SuspendResponse,
    TextToSpeechRequest,
    TextToSpeechResponse,
    TextToSpeechStreamRequest,
    TextToSpeechStreamResponse,
    TranscribeRequest,
    TranscribeResponse,
    TranscribeStreamRequest,
    TranscribeStreamResponse,
    TranslateRequest,
    TranslateResponse,
    UnloadModelRequest,
    UnloadModelResponse,
    UpscaleStreamRequest,
    UpscaleStreamResponse,
    VideoStreamRequest,
    VideoStreamResponse,
)


def bci_transcribe(
    transport: Transport, params: BciTranscribeRequest
) -> Iterator[BciTranscribeResponse]:
    payload = params.model_dump(mode="json", by_alias=True, exclude_unset=True)
    for chunk in transport.call_stream(payload):
        yield BciTranscribeResponse.model_validate(chunk)


def bci_transcribe_stream(
    transport: Transport, params: BciTranscribeStreamRequest, up: Iterable[bytes]
) -> Iterator[BciTranscribeStreamResponse]:
    payload = params.model_dump(mode="json", by_alias=True, exclude_unset=True)
    for chunk in transport.call_duplex(payload, up):
        yield BciTranscribeStreamResponse.model_validate(chunk)


def cancel(transport: Transport, params: CancelRequest) -> CancelResponse:
    payload = params.model_dump(mode="json", by_alias=True, exclude_unset=True)
    return CancelResponse.model_validate(transport.call(payload))


def classify(
    transport: Transport, params: ClassifyRequest
) -> Iterator[ClassifyResponse]:
    payload = params.model_dump(mode="json", by_alias=True, exclude_unset=True)
    for chunk in transport.call_stream(payload):
        yield ClassifyResponse.model_validate(chunk)


def completion_stream(
    transport: Transport, params: CompletionStreamRequest
) -> Iterator[CompletionStreamResponse]:
    payload = params.model_dump(mode="json", by_alias=True, exclude_unset=True)
    for chunk in transport.call_stream(payload):
        yield CompletionStreamResponse.model_validate(chunk)


def delete_cache(
    transport: Transport, params: DeleteCacheRequest
) -> DeleteCacheResponse:
    payload = params.model_dump(mode="json", by_alias=True, exclude_unset=True)
    return DeleteCacheResponse.model_validate(transport.call(payload))


def diffusion_stream(
    transport: Transport, params: DiffusionStreamRequest
) -> Iterator[DiffusionStreamResponse]:
    payload = params.model_dump(mode="json", by_alias=True, exclude_unset=True)
    for chunk in transport.call_stream(payload):
        yield DiffusionStreamResponse.model_validate(chunk)


def download_asset(
    transport: Transport, params: DownloadAssetRequest
) -> DownloadAssetResponse:
    payload = params.model_dump(mode="json", by_alias=True, exclude_unset=True)
    return DownloadAssetResponse.model_validate(transport.call(payload))


def download_asset_with_progress(
    transport: Transport, params: DownloadAssetRequest
) -> Iterator[ModelProgressResponse | DownloadAssetResponse]:
    # Progress events and the terminal reply both arrive through the
    # same stream, distinguished only by each payload's own `type` —
    # call_stream already falls back cleanly to a single terminal
    # chunk if the server ends up replying unary instead (e.g. an
    # operation that doesn't support progress for this method).
    payload = params.model_dump(mode="json", by_alias=True, exclude_unset=True)
    payload["withProgress"] = True
    for chunk in transport.call_stream(payload):
        if chunk.get("type") == "modelProgress":
            yield ModelProgressResponse.model_validate(chunk)
        else:
            yield DownloadAssetResponse.model_validate(chunk)


def embed(transport: Transport, params: EmbedRequest) -> EmbedResponse:
    payload = params.model_dump(mode="json", by_alias=True, exclude_unset=True)
    return EmbedResponse.model_validate(transport.call(payload))


def finetune(transport: Transport, params: FinetuneRequest) -> FinetuneResponse:
    payload = params.model_dump(mode="json", by_alias=True, exclude_unset=True)
    return FinetuneResponse.model_validate(transport.call(payload))


def finetune_with_progress(
    transport: Transport, params: FinetuneRequest
) -> Iterator[FinetuneProgressResponse | FinetuneResponse]:
    # Progress events and the terminal reply both arrive through the
    # same stream, distinguished only by each payload's own `type` —
    # call_stream already falls back cleanly to a single terminal
    # chunk if the server ends up replying unary instead (e.g. an
    # operation that doesn't support progress for this method).
    payload = params.model_dump(mode="json", by_alias=True, exclude_unset=True)
    payload["withProgress"] = True
    for chunk in transport.call_stream(payload):
        if chunk.get("type") == "finetune:progress":
            yield FinetuneProgressResponse.model_validate(chunk)
        else:
            yield FinetuneResponse.model_validate(chunk)


def get_loaded_model_info(
    transport: Transport, params: GetLoadedModelInfoRequest
) -> GetLoadedModelInfoResponse:
    payload = params.model_dump(mode="json", by_alias=True, exclude_unset=True)
    return GetLoadedModelInfoResponse.model_validate(transport.call(payload))


def get_model_info(
    transport: Transport, params: GetModelInfoRequest
) -> GetModelInfoResponse:
    payload = params.model_dump(mode="json", by_alias=True, exclude_unset=True)
    return GetModelInfoResponse.model_validate(transport.call(payload))


def heartbeat(transport: Transport, params: HeartbeatRequest) -> HeartbeatResponse:
    payload = params.model_dump(mode="json", by_alias=True, exclude_unset=True)
    return HeartbeatResponse.model_validate(transport.call(payload))


def load_model(transport: Transport, params: LoadModelRequest) -> LoadModelResponse:
    payload = params.model_dump(mode="json", by_alias=True, exclude_unset=True)
    return LoadModelResponse.model_validate(transport.call(payload))


def load_model_with_progress(
    transport: Transport, params: LoadModelRequest
) -> Iterator[ModelProgressResponse | LoadModelResponse]:
    # Progress events and the terminal reply both arrive through the
    # same stream, distinguished only by each payload's own `type` —
    # call_stream already falls back cleanly to a single terminal
    # chunk if the server ends up replying unary instead (e.g. an
    # operation that doesn't support progress for this method).
    payload = params.model_dump(mode="json", by_alias=True, exclude_unset=True)
    payload["withProgress"] = True
    for chunk in transport.call_stream(payload):
        if chunk.get("type") == "modelProgress":
            yield ModelProgressResponse.model_validate(chunk)
        else:
            yield LoadModelResponse.model_validate(chunk)


def logging_stream(
    transport: Transport, params: LoggingStreamRequest
) -> Iterator[LoggingStreamResponse]:
    payload = params.model_dump(mode="json", by_alias=True, exclude_unset=True)
    for chunk in transport.call_stream(payload):
        yield LoggingStreamResponse.model_validate(chunk)


def model_registry_get_model(
    transport: Transport, params: ModelRegistryGetModelRequest
) -> ModelRegistryGetModelResponse:
    payload = params.model_dump(mode="json", by_alias=True, exclude_unset=True)
    return ModelRegistryGetModelResponse.model_validate(transport.call(payload))


def model_registry_list(
    transport: Transport, params: ModelRegistryListRequest
) -> ModelRegistryListResponse:
    payload = params.model_dump(mode="json", by_alias=True, exclude_unset=True)
    return ModelRegistryListResponse.model_validate(transport.call(payload))


def model_registry_search(
    transport: Transport, params: ModelRegistrySearchRequest
) -> ModelRegistrySearchResponse:
    payload = params.model_dump(mode="json", by_alias=True, exclude_unset=True)
    return ModelRegistrySearchResponse.model_validate(transport.call(payload))


def ocr_stream(
    transport: Transport, params: OcrStreamRequest
) -> Iterator[OcrStreamResponse]:
    payload = params.model_dump(mode="json", by_alias=True, exclude_unset=True)
    for chunk in transport.call_stream(payload):
        yield OcrStreamResponse.model_validate(chunk)


def plugin_invoke(
    transport: Transport, params: PluginInvokeRequest
) -> PluginInvokeResponse:
    payload = params.model_dump(mode="json", by_alias=True, exclude_unset=True)
    return PluginInvokeResponse.model_validate(transport.call(payload))


def plugin_invoke_stream(
    transport: Transport, params: PluginInvokeStreamRequest
) -> Iterator[PluginInvokeStreamResponse]:
    payload = params.model_dump(mode="json", by_alias=True, exclude_unset=True)
    for chunk in transport.call_stream(payload):
        yield PluginInvokeStreamResponse.model_validate(chunk)


def provide(transport: Transport, params: ProvideRequest) -> ProvideResponse:
    payload = params.model_dump(mode="json", by_alias=True, exclude_unset=True)
    return ProvideResponse.model_validate(transport.call(payload))


def rag(transport: Transport, params: RagRequest) -> RagResponse:
    payload = params.model_dump(mode="json", by_alias=True, exclude_unset=True)
    return RagResponse.model_validate(transport.call(payload))


def rag_with_progress(
    transport: Transport, params: RagRequest
) -> Iterator[RagProgressResponse | RagResponse]:
    # Progress events and the terminal reply both arrive through the
    # same stream, distinguished only by each payload's own `type` —
    # call_stream already falls back cleanly to a single terminal
    # chunk if the server ends up replying unary instead (e.g. an
    # operation that doesn't support progress for this method).
    payload = params.model_dump(mode="json", by_alias=True, exclude_unset=True)
    payload["withProgress"] = True
    for chunk in transport.call_stream(payload):
        if chunk.get("type") == "rag:progress":
            yield RagProgressResponse.model_validate(chunk)
        else:
            yield RagResponse.model_validate(chunk)


def resume(transport: Transport, params: ResumeRequest) -> ResumeResponse:
    payload = params.model_dump(mode="json", by_alias=True, exclude_unset=True)
    return ResumeResponse.model_validate(transport.call(payload))


def state(transport: Transport, params: StateRequest) -> StateResponse:
    payload = params.model_dump(mode="json", by_alias=True, exclude_unset=True)
    return StateResponse.model_validate(transport.call(payload))


def stop_provide(
    transport: Transport, params: StopProvideRequest
) -> StopProvideResponse:
    payload = params.model_dump(mode="json", by_alias=True, exclude_unset=True)
    return StopProvideResponse.model_validate(transport.call(payload))


def suspend(transport: Transport, params: SuspendRequest) -> SuspendResponse:
    payload = params.model_dump(mode="json", by_alias=True, exclude_unset=True)
    return SuspendResponse.model_validate(transport.call(payload))


def text_to_speech(
    transport: Transport, params: TextToSpeechRequest
) -> Iterator[TextToSpeechResponse]:
    payload = params.model_dump(mode="json", by_alias=True, exclude_unset=True)
    for chunk in transport.call_stream(payload):
        yield TextToSpeechResponse.model_validate(chunk)


def text_to_speech_stream(
    transport: Transport, params: TextToSpeechStreamRequest, up: Iterable[bytes]
) -> Iterator[TextToSpeechStreamResponse]:
    payload = params.model_dump(mode="json", by_alias=True, exclude_unset=True)
    for chunk in transport.call_duplex(payload, up):
        yield TextToSpeechStreamResponse.model_validate(chunk)


def transcribe(
    transport: Transport, params: TranscribeRequest
) -> Iterator[TranscribeResponse]:
    payload = params.model_dump(mode="json", by_alias=True, exclude_unset=True)
    for chunk in transport.call_stream(payload):
        yield TranscribeResponse.model_validate(chunk)


def transcribe_stream(
    transport: Transport, params: TranscribeStreamRequest, up: Iterable[bytes]
) -> Iterator[TranscribeStreamResponse]:
    payload = params.model_dump(mode="json", by_alias=True, exclude_unset=True)
    for chunk in transport.call_duplex(payload, up):
        yield TranscribeStreamResponse.model_validate(chunk)


def translate(
    transport: Transport, params: TranslateRequest
) -> Iterator[TranslateResponse]:
    payload = params.model_dump(mode="json", by_alias=True, exclude_unset=True)
    for chunk in transport.call_stream(payload):
        yield TranslateResponse.model_validate(chunk)


def unload_model(
    transport: Transport, params: UnloadModelRequest
) -> UnloadModelResponse:
    payload = params.model_dump(mode="json", by_alias=True, exclude_unset=True)
    return UnloadModelResponse.model_validate(transport.call(payload))


def upscale_stream(
    transport: Transport, params: UpscaleStreamRequest
) -> Iterator[UpscaleStreamResponse]:
    payload = params.model_dump(mode="json", by_alias=True, exclude_unset=True)
    for chunk in transport.call_stream(payload):
        yield UpscaleStreamResponse.model_validate(chunk)


def video_stream(
    transport: Transport, params: VideoStreamRequest
) -> Iterator[VideoStreamResponse]:
    payload = params.model_dump(mode="json", by_alias=True, exclude_unset=True)
    for chunk in transport.call_stream(payload):
        yield VideoStreamResponse.model_validate(chunk)
